---
admin_data:
  :options:
    :git: :git://github.com/neerajdotname/admin_data.git
# cap_gun:
#   :options:
#     :git: :git://github.com/relevance/cap_gun.git
db_populate:
  :options:
    :git: :git://github.com/ffmike/db-populate.git
# fast_remote_cache:
#   :options:
#     :git: :git://github.com/37signals/fast_remote_cache.git
hashdown:
  :options:
    :git: :git://github.com/rubysolo/hashdown.git
# object_daddy:
#   :options:
#     :git: :git://github.com/flogic/object_daddy.git
# parallel_specs:
#   :options:
#     :git: :git://github.com/grosser/parallel_specs.git
# rack-bug:
#   :options:
#     :git: :git://github.com/brynary/rack-bug.git
# rails_xss:
#   :options:
#     :git: :git://github.com/NZKoz/rails_xss.git
#   :if: rails_branch == "2-3-stable"
# rcov_plugin:
#   :options:
#     :git: git://github.com/commondream/rcov_plugin.git
# rubaidhstrano:
#   :options:
#     :git: :git://github.com/ffmike/rubaidhstrano.git
# shmacros:
#   :options:
#     :git: :git://github.com/maxim/shmacros.git
stringex:
  :options:
    :git: :git://github.com/rsl/stringex.git
# superdeploy:
#   :options:
#     :git: :git://github.com/saizai/superdeploy.git
# time-warp:
#   :options:
#     :git: :git://github.com/iridesco/time-warp.git
# validation_reflection:
#   :options:
#     :git: :git://github.com/redinger/validation_reflection.git

# Optional monitoring
new_relic:
  :options:
    :git: :git://github.com/newrelic/rpm.git
  :if: monitoring == "new_relic"

# Optional exception handling
exceptional:
  :options:
    :git: :git://github.com/contrast/exceptional.git
  :if: exception_handling == "exceptional"
